"""Smoke test for gtable_py._biobabel.

Generated by `biobabel new contract`. Edit to actually exercise the package's
public API (this template only verifies importability).
"""

from __future__ import annotations


def main() -> None:
    import gtable_py  # noqa: F401
    print("imported gtable_py successfully")


if __name__ == "__main__":
    main()
